### PR TITLE
[fr] typos + official translations

### PR DESCRIPTION
**Pull request by code-elegant**
https://en.wikipedia.org/wiki/JavaScript
http://www.culture.fr/franceterme/terme/INFO58
http://www.cnrtl.fr/definition/pr%C3%A9dictibilit%C3%A9

### CODE REVIEW

**Comment by yatil** [comment]
@code-elegant Thank you!

@notabene Can you review this Pull Request?

**Comment by notabene** [comment]
@code-elegant thank you for the review.
@yatil planned for next week, thanks for the heads-up.

**Comment by notabene** [comment]
Ah, what the hell, I just looked at the PR and it meant 3 minutes tops. All good for me @yatil 👍

**Review by notabene — APPROVED** [review]

**Comment by yatil** [comment]
@notabene Perfect, thanks!
@code-elegant How do you want to be recognized as a contributor? (Your profile doesn’t list a name, and I’m happy to just use your GitHub username, but want to check first :-D)

**Comment by code-elegant** [comment]
@yatil : please use my pseudo, it's sufficient.
@notabene : Thanx. I’ll probably will soon push a few translations, too.

**Comment by yatil** [comment]
@code-elegant 👍🏼

**Pull request merged**
