### PR TITLE
[ready to publish] KO - Principles

### PR DESCRIPTION
**Pull request by yonguilee**

### CODE REVIEW

**Comment by yonguilee** [comment]
@slhenry ,@yatil, KO translation is done and also reviewed.
It can be published. :)

Reviewer info : Jun Ho Lee (gomjunho@gmail.com)

**Comment by shawna-slh** [comment]
Hi Yong Ui Lee,

Thank you for this translation! It is a long page, and must have been a lot of work.

I see one possible overall issue with the level 3 headings -- that are preceded with ###

These should be simple statements -- and without terminal punctuation (periods).
They should **_not_** be instructions or full sentences.

For example:
* "Text alternatives for non-text content" (translation should not include the idea "you must provide")
* "Text is readable and understandable" (translation should not include the idea "should be" -- just that it is :-)

Would you re-consider the translations of the level 3 headings?
Let me know if you would like to discuss issues with presenting such information in Korean.

**Comment by yonguilee** [comment]
@slhenry , ok! I will check all level 3 heading. When I'm done, I'll let you know by mentioning in comment :) Have a nice holiday !!

**Comment by yonguilee** [comment]
@slhenry, I fixed the level3 titles ! Check it please :)

**Comment by shawna-slh** [comment]
Thanks @yonguilee ! (Sorry for my delay in getting to this.)

**Review by shawna-slh — APPROVED** [review]

**Pull request merged**
