### PR TITLE
[Ready for Review] Indonesian - Accessibility Principles

### LINKED ISSUE #72: [Indonesian] Accessibility Principles
Original page: https://www.w3.org/WAI/fundamentals/accessibility-principles/

Translator: [frirasyidi](https://github.com/frirasyidi)

PR opened: https://github.com/w3c/wai-accessibility-principles/pull/42

### PR DESCRIPTION
**Pull request by frirasyidi**
Add Bahasa Indonesia translation of index.md

### CODE REVIEW

**Review by Adiltonzs — APPROVED** [review]

**Comment by remibetin** [comment]
@frirasyidi What is the status of this PR?

**Comment by frirasyidi** [comment]
@remibetin looking at the history, @Adiltonzs seems to have reviewed and approved the translation.

I didn't realize that this was reopened and I haven't checked yet if there's anything needs to be changed. Will do sometime tomorrow.

**Comment by frirasyidi** [comment]
@remibetin I have taken a look and decided that some changes are needed in the text to make some paragraphs clearer. The new translation is best to be reviewed again.

Good news is I have found some people who can help me review the translations. I'll inform them soon to do a review on this translation---despite that, @Adiltonzs, you are encouraged to also recheck. :-)

**Comment by remibetin** [comment]
@frirasyidi Please note that the content of this repository has been moved. I have therefore re-created your PR at https://github.com/w3c/wai-website/pull/840

**Pull request closed without merging**
